version: '3.2'
services:
  db:
    image: postgres

  web:
    environment:
      - IS_DOCKER=true
    build:
        context: .
        dockerfile: Dockerfile.development
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./scripts/run.sh
